### ISSUE TITLE
I encountered the same problem as #70

### ISSUE THREAD

**Issue by rcone11** [robotology/blockfactory#78]
I encountered the same problem and followed the instructions on the webpage export BLOCKFACTORY_PLUGIN_PATH=/home/han/blockfactory/example/build. “SUCCESS: Block ‘SignalMath’ found and loaded from plugin ‘ExampleToolbox’” appeared, but I still received an error in Simulink: Error reported by S-function ‘BlockFactory’ in ‘Model/w// mask’: Failed to create factory. Factory error (2): ExampleToolbox: cannot open shared object file: No such file or directory. Failed to get factory object (className=SignalMath, libName=ExampleToolbox). Failed to get the factory.

_Originally posted by @rcone11 in https://github.com/robotology/blockfactory/issues/70#issuecomment-2095141825_

**Comment by traversaro** [comment]
@rcone11 did you solved the problem? Note that the issue is closed at the moment.
